### ISSUE TITLE
USB port mechanical design

### ISSUE THREAD

**Issue by sarahfenway** [kirknorthrop/circuitpython-badge#10]
USB port soldering is weak on the mechanical pins at the side

**Comment by deshipu** [comment]
We can use a different USB port. Any suggestions?

**Comment by sarahfenway** [comment]
I added this mainly as a point that occurred - I suspect a good part of this is "hand soldered prototype" - but I wonder if there are ports which offer through hole mechanical pins instead.

**Comment by deshipu** [comment]
I just used that particular USB socket because that's what I have on hand, but we can of course use any kind we want, the prices are similar and the cost of the two additional through-hole solderpoints is negligible.

**Comment by AidanTek** [comment]
Something like this might help avoid accidents: [Micro-USB](https://uk.rs-online.com/web/p/micro-usb-connectors/1725335/)

**Comment by deshipu** [comment]
That looks good, I will be sure to use that footprint when design the next iteration.

**Comment by AidanTek** [comment]
I'd be willing to bet that we can find a cheaper equivalent as well
