### ISSUE TITLE
Radio communication

### ISSUE THREAD

**Issue by deshipu** [kirknorthrop/circuitpython-badge#17]
The prototypes have an NRF24L01+ module installed on them, which allows for a simple packet radio communication between them. However, there is at the moment no library that would allow for easy use of that functionality. This ticket is for developing such a library.

There is a library for this module for MicroPython, so we can steal most of the code from there: https://github.com/micropython/micropython/tree/master/drivers/nrf24l01

In terms of API, however, I think it would be great to simplify it somewhat and use something similar to the radio API on the micro:bit: https://microbit-micropython.readthedocs.io/en/latest/radio.html

The NRF24 chip uses a packet radio protocol very similar to the one used by the NRF51 on the micro:bit, however there seem to be some crucial differences between the two somewhere at a very low level, because despite devoting two weeks to making them communicate, I failed. I can't really confirm this without proper tools (an SDR capable of listening to 2.4GHz transmissions), but I suspect there is some incompatibility there in the signal encoding that makes communication impossible.

We will want to have that library frozen into the firmware, so that it's always available and so that it doesn't consume extra memory when imported.

**Comment by deshipu** [comment]
Alternatively, we could consider other means of communication, especially if we can find something that doesn't work in the 2.4GHz spectrum, which is likely to be quite busy on a conference (both WiFi an bluetooth use that frequency).

**Comment by sarahfenway** [comment]
You’d also want to hit as wide an area as possible - what I mean is that in Europe we can easily find common ground, but it would be great to also ensure we can be used in the US too. Eg 2.4GHz is congested, but it is congested for a reason - 433MHz is great in Europe but less so in the US. 2.4GHz is also great because the antenna is so short - 433MHz is about 70cm.

**Comment by deshipu** [comment]
We could also go for something more exotic, like IR, NFC or even ultrasound.

**Comment by sarahfenway** [comment]
IR is happily left in the 1990s I think ;)

Ultrasound intrigues me, I heard that Google use it for some things now.

**Comment by deshipu** [comment]
I think that IR could be a very good solution here, mostly because it's line-of-sight, so you limit the interference with other people. It could allow for very interesting mechanics, where the badges could "recognize" each other when they come into each other's field of view. Plus both the sensors and the IR LEDs are dirt-cheap and possible to debug with a cellphone camera.

**Comment by AidanTek** [comment]
IR is probably a very sensible option - the NRF24l01 is ok - but I never saw a situation where even 10 people were trying to use them at once :P 

Share some links for ultrasound if you have them!
